import {
  AppWindow,
  Award,
  Banknote,
  Boxes,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  ChartColumn,
  ClipboardCheck,
  Clock,
  Cloud,
  CodeXml,
  Coins,
  Compass,
  CreditCard,
  Database,
  Eye,
  Factory,
  FileSpreadsheet,
  FileText,
  FlaskConical,
  Gauge,
  Gavel,
  Globe,
  Handshake,
  Headset,
  Heart,
  HeartPulse,
  House,
  Infinity as InfinityIcon,
  Landmark,
  Layers,
  LayoutTemplate,
  LifeBuoy,
  Lock,
  Megaphone,
  MessageSquare,
  Monitor,
  Network,
  Palette,
  PenTool,
  Plane,
  Puzzle,
  Receipt,
  RefreshCw,
  Rocket,
  Scale,
  ScrollText,
  Search,
  Server,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Siren,
  Smartphone,
  Sparkles,
  Target,
  Timer,
  TrendingUp,
  UserCheck,
  Users,
  Wallet,
  Workflow,
  Wrench,
  Zap,
  type LucideProps,
} from "lucide-react";

/**
 * Icon registry. Content files reference icons by name (a plain string),
 * which keeps them serialisable across the server/client boundary.
 */
const icons = {
  appWindow: AppWindow,
  award: Award,
  banknote: Banknote,
  boxes: Boxes,
  briefcase: Briefcase,
  building: Building2,
  calculator: Calculator,
  calendar: Calendar,
  chart: ChartColumn,
  clipboardCheck: ClipboardCheck,
  clock: Clock,
  cloud: Cloud,
  code: CodeXml,
  coins: Coins,
  compass: Compass,
  creditCard: CreditCard,
  database: Database,
  eye: Eye,
  factory: Factory,
  fileSpreadsheet: FileSpreadsheet,
  fileText: FileText,
  flask: FlaskConical,
  gauge: Gauge,
  gavel: Gavel,
  globe: Globe,
  handshake: Handshake,
  headset: Headset,
  heart: Heart,
  heartPulse: HeartPulse,
  house: House,
  infinity: InfinityIcon,
  landmark: Landmark,
  layers: Layers,
  layout: LayoutTemplate,
  lifeBuoy: LifeBuoy,
  lock: Lock,
  megaphone: Megaphone,
  message: MessageSquare,
  monitor: Monitor,
  network: Network,
  palette: Palette,
  pen: PenTool,
  plane: Plane,
  puzzle: Puzzle,
  receipt: Receipt,
  refresh: RefreshCw,
  rocket: Rocket,
  scale: Scale,
  scroll: ScrollText,
  search: Search,
  server: Server,
  share: Share2,
  shield: ShieldCheck,
  cart: ShoppingCart,
  siren: Siren,
  smartphone: Smartphone,
  sparkles: Sparkles,
  target: Target,
  timer: Timer,
  trending: TrendingUp,
  userCheck: UserCheck,
  users: Users,
  wallet: Wallet,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
} as const;

export type IconName = keyof typeof icons;

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" focusable="false" {...props} />;
}

/** LinkedIn glyph (brand icons are not shipped by lucide). */
export function LinkedInIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false" {...props}>
      <path d="M20.45 20.45h-3.56v-5.57c0-1.33-.03-3.04-1.85-3.04-1.86 0-2.14 1.45-2.14 2.94v5.67H9.34V9h3.42v1.56h.05c.48-.9 1.64-1.85 3.37-1.85 3.6 0 4.27 2.37 4.27 5.46v6.28zM5.34 7.43a2.06 2.06 0 1 1 0-4.13 2.06 2.06 0 0 1 0 4.13zM7.12 20.45H3.56V9h3.56v11.45zM22.22 0H1.77C.79 0 0 .77 0 1.73v20.54C0 23.23.79 24 1.77 24h20.45c.98 0 1.78-.77 1.78-1.73V1.73C24 .77 23.2 0 22.22 0z" />
    </svg>
  );
}
